/**
 * WEBFLASH-TAXONOMY-RECONCILE-001 — room-preset taxonomy and commercial-claim
 * guards.
 *
 * Reconciles the WebFlash customer surface with the approved Sense360
 * taxonomy (SOT-BUNDLE-TAXONOMY-001 in sense360store/SOT, merged as
 * 8df6ad69cb1dc76119843eecddcbd4fa2df4c33d) and the upstream taxonomy audit
 * (PRODUCT-TAXONOMY-AUDIT-001 in sense360store/esphome-public). The rules
 * this suite pins:
 *
 *   - A visible WebFlash entry is a ROOM / FIRMWARE PRESET, never a claim of
 *     commercial availability. SOT owns commercial names, status, visibility
 *     and buyability; esphome-public owns board identity and firmware
 *     lifecycle; the WebFlash manifest owns what is actually served.
 *   - The SOT commercial surface is mirrored into
 *     scripts/data/sot-commercial-mirror.json (synchronized evidence with
 *     provenance, regenerated by scripts/refresh-sot-mirror.py — never
 *     hand-authored, never authority).
 *   - Customer copy is room/use-case led, keeps board names and config
 *     strings visible as technical detail, and never uses Base/Pro/model/
 *     variant tiers, "on sale"/"buy" language, or internal programme IDs.
 *   - Hardware wording matches the verified board evidence: RoomIQ radar
 *     modules are connector-attached, SPS30 / IR temperature are external
 *     connector options, the AirIQ formaldehyde (SFA30/SFA40) fitment is
 *     unresolved and never advertised, and no voice/microphone SKU is
 *     implied.
 *
 * Anti-tautology: kits.json is always compared against a DIFFERENT source
 * (the SOT mirror, the manifest, the expected-surface fixture), and the SOT
 * mirror's own posture flags are re-derived from its bundle rows.
 */
import { describe, expect, test } from '@jest/globals';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DISALLOWED_TOKEN_MIGRATIONS } from '../scripts/validate-naming-policy.js';
import { parseConfigParams } from '../scripts/utils/url-config.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(__dirname, '..');

const read = rel => fs.readFileSync(path.join(REPO_ROOT, rel), 'utf8');
const readJson = rel => JSON.parse(read(rel));

const kitsJson = readJson('scripts/data/kits.json');
const kits = kitsJson.kits;
const mirror = readJson('scripts/data/sot-commercial-mirror.json');
const manifest = readJson('manifest.json');
const manifestConfigs = new Set(
    (manifest.builds || []).map(b => b.config_string).filter(Boolean)
);

const moduleRequirementsSource = read('scripts/data/module-requirements.js');
const dataJsSource = read('scripts/data.js');
const identifySource = read('scripts/identify.js');
const appSource = read('scripts/app.js');
const stateSource = read('scripts/state.js');

// Customer-facing string fields collected from kits.json.
function kitCustomerStrings(kit) {
    return [
        kit.display_name,
        kit.description,
        kit.room_label,
        ...(kit.recommended_rooms || []),
        ...(kit.notes || []),
        ...(kit.known_limitations || []),
        ...(kit.components || []).map(c => c.label)
    ].filter(Boolean);
}

describe('SOT commercial-surface mirror — provenance and posture', () => {
    test('the mirror carries full provenance and is labelled as evidence, not authority', () => {
        expect(mirror.provenance.source_repo).toBe('sense360store/SOT');
        expect(mirror.provenance.source_sha).toMatch(/^[0-9a-f]{40}$/);
        expect(mirror.provenance.source_files).toContain('bundles.yaml');
        expect(mirror.provenance.generator).toBe('scripts/refresh-sot-mirror.py');
        expect(mirror.role).toMatch(/mirror/i);
        expect(mirror.role).toMatch(/not commercial authority/i);
        expect(mirror.role).toMatch(/refresh-sot-mirror/);
    });

    test('schema drift gate: version, provenance date and every row shape hold', () => {
        // SENSE360-CANONICALISATION-001 PR 13: CI has no SOT checkout, so the
        // checked-in mirror's schema and derivations are validated offline in
        // both suites (this one and __tests__/python/test_refresh_sot_mirror.py).
        const BUNDLE_STATUSES = new Set([
            'concept', 'planned', 'preview', 'available', 'paused', 'retired'
        ]);
        expect(mirror.schema_version).toBe(1);
        expect(mirror.provenance.source_commit_date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
        mirror.bundles.forEach(bundle => {
            ['id', 'name', 'status', 'visibility'].forEach(field => {
                expect(bundle[field]).toBeTruthy();
            });
            expect(BUNDLE_STATUSES.has(bundle.status)).toBe(true);
            expect(bundle.commercially_available).toBe(bundle.status === 'available');
            expect(bundle.buyable).toBe(bundle.status === 'available');
            expect(bundle.renderable).toBe(bundle.visibility === 'public');
        });
    });

    test('the posture flags are consistent with the bundle rows (no internal drift)', () => {
        const anyAvailable = mirror.bundles.some(b => b.commercially_available);
        const anyBuyable = mirror.bundles.some(b => b.buyable);
        expect(mirror.commercial_posture.any_bundle_available).toBe(anyAvailable);
        expect(mirror.commercial_posture.any_bundle_buyable).toBe(anyBuyable);
    });

    test('as mirrored from SOT, no bundle is available or buyable today', () => {
        // If SOT ever flips a bundle to available/buyable, this fails loud so
        // the copy rules below get deliberately revisited instead of silently
        // staying over-restrictive or (worse) silently claiming availability.
        expect(mirror.commercial_posture.any_bundle_available).toBe(false);
        expect(mirror.commercial_posture.any_bundle_buyable).toBe(false);
    });

    test('the paused Air Quality Starter record has no firmware config and can never back a preset', () => {
        const legacy = mirror.bundles.find(b => b.id === 'air-quality-starter');
        expect(legacy).toBeTruthy();
        expect(legacy.status).toBe('paused');
        expect(legacy.buyable).toBe(false);
        expect(legacy.webflash_config == null).toBe(true);
    });
});

describe('room presets — schema and SOT/manifest joins', () => {
    test('every visible preset carries the room-preset schema fields', () => {
        expect(kits.length).toBeGreaterThan(0);
        kits.forEach(kit => {
            expect(typeof kit.room_label).toBe('string');
            expect(kit.room_label.length).toBeGreaterThan(0);
            expect(Array.isArray(kit.recommended_rooms)).toBe(true);
            expect(kit.recommended_rooms.length).toBeGreaterThan(0);
            expect(kit.presentation).toBe('firmware-preset');
            expect(typeof kit.commercial_bundle_id).toBe('string');
        });
    });

    test('every visible preset joins to its SOT bundle record by id, name, config, contents and rooms', () => {
        kits.forEach(kit => {
            const bundle = mirror.bundles.find(b => b.id === kit.commercial_bundle_id);
            expect(bundle).toBeTruthy();
            // Names and firmware mapping may never drift from SOT.
            expect(kit.display_name).toBe(bundle.name);
            expect(kit.firmware_config_string).toBe(bundle.webflash_config);
            expect(kit.recommended_rooms).toEqual(bundle.recommended_rooms);
            // Technical contents match the SOT physical bundle contents.
            const kitSkus = (kit.components || []).map(c => c.sku).sort();
            expect(kitSkus).toEqual([...bundle.contents].sort());
        });
    });

    test('no visible preset maps to a paused or concept SOT bundle', () => {
        kits.forEach(kit => {
            const bundle = mirror.bundles.find(b => b.id === kit.commercial_bundle_id);
            expect(['paused', 'concept']).not.toContain(bundle.status);
        });
    });

    test('every visible preset resolves to a served manifest build', () => {
        kits.forEach(kit => {
            expect(manifestConfigs.has(kit.firmware_config_string)).toBe(true);
        });
    });

    test('stable served firmware does not surface hidden SOT bundles (Kitchen stays withheld)', () => {
        // Ceiling-POE-AirIQ-RoomIQ is served stable, but its SOT bundle
        // (kitchen-poe) is hidden / non-buyable pending OD-SOT-009 — firmware
        // existence is never permission to expose a room card.
        const kitchen = mirror.bundles.find(b => b.id === 'kitchen-poe');
        expect(kitchen).toBeTruthy();
        expect(kitchen.buyable).toBe(false);
        expect(manifestConfigs.has(kitchen.webflash_config)).toBe(true);
        expect(kits.some(k => k.firmware_config_string === kitchen.webflash_config)).toBe(false);
        expect(kits.some(k => k.commercial_bundle_id === 'kitchen-poe')).toBe(false);
    });

    test('identical hardware is one preset with several recommended rooms, never duplicate cards', () => {
        const byConfig = new Map();
        kits.forEach(kit => {
            byConfig.set(kit.firmware_config_string, (byConfig.get(kit.firmware_config_string) || 0) + 1);
        });
        byConfig.forEach(count => expect(count).toBe(1));
        // The Bedroom / general-room preset covers its rooms via labels.
        const bedroom = kits.find(k => k.commercial_bundle_id === 'bedroom-poe');
        expect(bedroom).toBeTruthy();
        expect(bedroom.recommended_rooms.length).toBeGreaterThanOrEqual(2);
    });

    test('the Bathroom preset stays the only installer default / recommendation, framed as firmware', () => {
        const recommended = kits.filter(k => k.recommended);
        expect(recommended.map(k => k.commercial_bundle_id)).toEqual(['bathroom-poe']);
        const bathroom = recommended[0];
        expect(bathroom.firmware_config_string).toBe('Ceiling-POE-VentIQ-RoomIQ');
        expect(bathroom.firmware_channel).toBe('stable');
        // Its SOT record stays planned / not listed — the installer default is
        // a firmware recommendation, never a commercial claim.
        const bundle = mirror.bundles.find(b => b.id === 'bathroom-poe');
        expect(bundle.status).toBe('planned');
        expect(bundle.buyable).toBe(false);
    });
});

describe('customer copy — presets are firmware presets, never commercial listings', () => {
    const BANNED_COMMERCE = /\b(buy now|buy\b|on sale|in stock|add to cart|checkout|order now|price|prices|pricing|shop now|available bundle|commercially available|commercially released)\b/i;
    const BANNED_TIERS = /\b(base|pro|basic)\b/i;
    const INTERNAL_IDS = /\b(OD-SOT-\d+|[A-Z]{2,}(?:-[A-Z0-9]{2,})+-\d{3})\b/;

    test('no kits.json customer string carries commerce, tier or internal-ID language', () => {
        kits.forEach(kit => {
            kitCustomerStrings(kit).forEach(text => {
                expect(text).not.toMatch(BANNED_COMMERCE);
                expect(text).not.toMatch(BANNED_TIERS);
                expect(text).not.toMatch(INTERNAL_IDS);
            });
        });
    });

    test('descriptions no longer call a preset "the recommended Sense360 kit"', () => {
        kits.forEach(kit => {
            expect(kit.description.toLowerCase()).not.toContain('recommended sense360 kit');
            expect(kit.description.toLowerCase()).not.toContain('buyable');
        });
    });

    test('the view leads with the room choice and keeps technical detail secondary', () => {
        // Room-led landing (the binding customer UX decision).
        expect(identifySource).toContain('Choose your room');
        // Firmware-preset framing, not current-buyable-kit framing.
        expect(identifySource).toMatch(/firmware preset/i);
        // The config string stays visible as the secondary technical
        // identifier (the B__target line renders the resolved config string).
        expect(identifySource).toContain("h('span', { class: 'B__target' }");
        // No commerce language in the render layer.
        expect(identifySource).not.toMatch(/buy now|on sale|add to cart|price/i);
        expect(appSource).not.toMatch(/buy now|on sale|add to cart/i);
    });

    test('the retired planned-kit marketing strip (TRIAC teaser) is gone from the view data', () => {
        expect(dataJsSource).not.toContain('TRIAC Fan Control');
        expect(dataJsSource).not.toMatch(/export const PLANNED/);
    });
});

describe('hardware wording — board claims match verified evidence', () => {
    test('RoomIQ radar modules (LD2450, SEN0609) are described as connector-attached, never PCB-mounted', () => {
        const roomiqLines = moduleRequirementsSource
            .split('\n')
            .filter(line => /LD2450|SEN0609/.test(line));
        expect(roomiqLines.length).toBeGreaterThan(0);
        roomiqLines.forEach(line => {
            expect(line).toMatch(/connector/i);
        });
        // The advanced-builder card copy in data.js follows the same rule.
        dataJsSource.split('\n')
            .filter(line => /LD2450|SEN0609/.test(line))
            .forEach(line => expect(line).toMatch(/connector/i));
    });

    test('no definitive SFA30 claim remains anywhere in the runtime data or module copy', () => {
        expect(moduleRequirementsSource).not.toContain('SFA30');
        expect(dataJsSource).not.toContain('SFA30');
        expect(stateSource).not.toContain('SFA30');
    });

    test('formaldehyde is only ever described as fitment-unresolved, never as a supported function', () => {
        const lines = moduleRequirementsSource
            .split('\n')
            .filter(line => /SFA40|formaldehyde|HCHO/i.test(line));
        // Whenever the topic appears it must carry the unresolved qualifier;
        // a definitive "SFA40 connector" or "formaldehyde sensing" claim fails.
        lines.forEach(line => {
            expect(line).toMatch(/unresolved|not currently exposed/i);
        });
    });

    test('SPS30 is always an external, optional connector attachment', () => {
        const lines = [
            ...moduleRequirementsSource.split('\n'),
            ...dataJsSource.split('\n')
        ].filter(line => /SPS30/.test(line));
        expect(lines.length).toBeGreaterThan(0);
        lines.forEach(line => {
            expect(line).toMatch(/connector|external|optional|not included/i);
        });
    });

    test('AirIQ copy claims indices, not particulate coverage or gas concentrations', () => {
        // The advanced-builder AirIQ card must not advertise particulate
        // coverage (PM needs the external SPS30) or calibrated CO / NO2.
        expect(dataJsSource).not.toMatch(/particulate coverage/i);
        expect(moduleRequirementsSource).not.toMatch(/CO concentration|NO2 concentration/i);
    });

    test('VentIQ external sensors are connector options and RoomIQ owns temperature/humidity in combined presets', () => {
        const ventiqBlock = moduleRequirementsSource.slice(
            moduleRequirementsSource.indexOf('ventiq: {'),
            moduleRequirementsSource.indexOf('fan: {')
        );
        expect(ventiqBlock).toMatch(/IR (surface-)?temperature[^\n]*(connector|optional)/i);
        // The 2.0 card copy must not claim VentIQ measures temperature or
        // humidity itself (SGP41 is the only on-board sensor).
        const ventiqCard = dataJsSource.split('\n').find(l => l.includes("id: 'ventiq'") || l.includes('S360-211'));
        expect(ventiqCard).toBeTruthy();
        const ventiqDesc = dataJsSource.slice(dataJsSource.indexOf("id: 'ventiq'"), dataJsSource.indexOf('bathroom: true'));
        expect(ventiqDesc).not.toMatch(/desc: '[^']*\b(humidity|temperature)\b[^']*'/i);
    });

    test('no voice / microphone SKU is implied by LED or builder copy', () => {
        expect(dataJsSource).not.toMatch(/microphone|voice-enabled/i);
        const ledBlock = moduleRequirementsSource.slice(
            moduleRequirementsSource.indexOf('led: {'),
            moduleRequirementsSource.length
        );
        expect(ledBlock).not.toMatch(/microphone|voice models|voice-enabled/i);
    });

    test('stale power / LED labels are gone from the engine label tables', () => {
        expect(stateSource).not.toContain("'PoE module'");
        expect(stateSource).not.toContain("'PWR module'");
        expect(stateSource).not.toContain("'LED Ring'");
        expect(stateSource).not.toContain("'No LED ring'");
        expect(stateSource).not.toContain("'Base Firmware'");
    });

    test('the nonexistent bare Ceiling-POE-AirIQ config is never referenced by runtime data', () => {
        // (The SOT mirror is exempt here: it faithfully records SOT's own
        // statement that this config exists in NO build matrix or manifest —
        // a negative historical record, not a reference to a real config.)
        const bare = /Ceiling-POE-AirIQ(?![-A-Za-z])/;
        expect(read('scripts/data/kits.json')).not.toMatch(bare);
        expect(dataJsSource).not.toMatch(bare);
        expect(moduleRequirementsSource).not.toMatch(bare);
        // And no mirror bundle ever declares it as its live firmware config.
        mirror.bundles.forEach(bundle => {
            if (bundle.webflash_config) {
                expect(bundle.webflash_config).not.toMatch(bare);
            }
        });
    });
});

describe('legacy aliases — read-time compatibility preserved, canonical output only', () => {
    // The audit table (docs: DEVELOPER.md "Legacy token and alias audit").
    // Read-time URL aliases must keep resolving to canonical wizard values.
    const URL_ALIAS_TABLE = [
        // [query, field, expected canonical wizard value]
        ['core=core&mount=wall&power=poe', 'mount', 'ceiling'],
        ['core=core&mount=ceiling&power=pwr', 'power', 'pwr'],
        ['core=base&mount=ceiling&power=poe', 'core', 'none'],
        ['core=core&mount=ceiling&power=poe&airiq=base', 'airiq', 'airiq'],
        ['core=core&mount=ceiling&power=poe&airiq=airiqbase', 'airiq', 'airiq'],
        ['core=core&mount=ceiling&power=poe&airiq=pro', 'airiq', 'ventiq'],
        ['core=core&mount=ceiling&power=poe&airiq=airiqprov', 'airiq', 'ventiq'],
        ['core=core&mount=ceiling&power=poe&bathroomairiq=base', 'bathroomairiq', 'ventiq'],
        ['core=core&mount=ceiling&power=poe&bathroomairiq=bathroomairiqpro', 'bathroomairiq', 'ventiq'],
        ['core=core&mount=ceiling&power=poe&fan=base', 'fan', 'pwm'],
        ['core=core&mount=ceiling&power=poe&roomiq=base', 'roomiq', 'roomiq'],
        ['core=core&mount=ceiling&power=poe&led=base', 'led', 'led']
    ];

    test.each(URL_ALIAS_TABLE)('legacy URL "%s" still resolves (%s → %s)', (query, field, expected) => {
        const parsed = parseConfigParams(query);
        expect(parsed.isValid).toBe(true);
        expect(parsed.sanitizedConfig[field]).toBe(expected);
    });

    test('canonical output segments never contain generic Fan or Base/Pro tokens', () => {
        const parsed = parseConfigParams(
            'core=core&mount=ceiling&power=poe&bathroomairiq=pro&roomiq=base&fan=base'
        );
        expect(parsed.isValid).toBe(true);
        expect(parsed.configKey).toBe('Ceiling-POE-RoomIQ-VentIQ-FanPWM');
        expect(parsed.configKey).not.toMatch(/Base|Pro(?!E)|(^|-)Fan(-|$)/);
    });

    test('the naming-policy migration table matches its documented canonical targets', () => {
        // DEVELOPER.md / CLAUDE.md previously documented AirIQProv → AirIQPro
        // and BathroomAirIQ → Bathroom; the validator is the source of truth
        // and every AirIQ-family legacy token collapses to AirIQ, every
        // BathroomAirIQ-family token to VentIQ.
        expect(DISALLOWED_TOKEN_MIGRATIONS).toEqual({
            AirIQProv: 'AirIQ',
            AirIQPro: 'AirIQ',
            AirIQBase: 'AirIQ',
            BathroomAirIQ: 'VentIQ',
            BathroomAirIQBase: 'VentIQ',
            BathroomAirIQPro: 'VentIQ',
            FanAnalog: 'FanDAC'
        });
        const docs = read('DEVELOPER.md');
        expect(docs).not.toMatch(/`AirIQProv`\s*→\s*migrate to\s*`AirIQPro`/);
        expect(docs).not.toMatch(/`BathroomAirIQ`\s*→\s*migrate to\s*`Bathroom`/);
        const claude = read('CLAUDE.md');
        expect(claude).not.toMatch(/`AirIQProv`\s*→\s*`AirIQPro`/);
        expect(claude).not.toMatch(/`BathroomAirIQ`\s*→\s*`Bathroom`(?!Air)/);
    });
});

describe('documentation — stale hardware claims corrected in current docs', () => {
    const CURRENT_DOCS = ['CLAUDE.md', 'DEVELOPER.md', 'docs/user-guide.md', 'docs/hardware-options.md'];

    test('no current doc keeps a definitive SFA30 connector claim', () => {
        CURRENT_DOCS.forEach(doc => {
            expect(read(doc)).not.toMatch(/SFA30/);
        });
    });

    test('current docs mark the RoomIQ radar modules as connector-attached', () => {
        CURRENT_DOCS.forEach(doc => {
            const text = read(doc);
            text.split('\n')
                .filter(line => /LD2450|SEN0609/.test(line))
                .forEach(line => expect(line).toMatch(/connector/i));
        });
    });
});
